language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # GraphViz
  - sudo apt-get install -qq graphviz

script: 
  - qmake
  - make
  - ./travis_qmake_gcc_cpp17_boost_graph
